// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CurseForgeFileData`, `CurseForgeFileResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Stream<DownloadProgress> downloadCurseforgeMods({
  required String instancePath,
  required List<int> fileIds,
  required String apiKey,
}) => RustLib.instance.api.crateApiDownloaderDownloadCurseforgeMods(
  instancePath: instancePath,
  fileIds: fileIds,
  apiKey: apiKey,
);

class DownloadProgress {
  final int totalFiles;
  final int downloadedFiles;
  final String currentFile;

  const DownloadProgress({
    required this.totalFiles,
    required this.downloadedFiles,
    required this.currentFile,
  });

  @override
  int get hashCode =>
      totalFiles.hashCode ^ downloadedFiles.hashCode ^ currentFile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgress &&
          runtimeType == other.runtimeType &&
          totalFiles == other.totalFiles &&
          downloadedFiles == other.downloadedFiles &&
          currentFile == other.currentFile;
}
