// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `scan_single_instance`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<ImportableInstance>> scanCurseforgeInstances() =>
    RustLib.instance.api.crateApiImporterScanCurseforgeInstances();

class ImportableInstance {
  final String name;
  final String mcVersion;
  final String modloader;
  final String path;
  final String? iconPath;
  final String source;

  const ImportableInstance({
    required this.name,
    required this.mcVersion,
    required this.modloader,
    required this.path,
    this.iconPath,
    required this.source,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      mcVersion.hashCode ^
      modloader.hashCode ^
      path.hashCode ^
      iconPath.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportableInstance &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          mcVersion == other.mcVersion &&
          modloader == other.modloader &&
          path == other.path &&
          iconPath == other.iconPath &&
          source == other.source;
}
