// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_base_dir`, `get_default_instance_dir`, `get_settings_file_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<LauncherSettings> loadSettings() =>
    RustLib.instance.api.crateApiSettingsManagerLoadSettings();

Future<void> saveSettings({required LauncherSettings settings}) => RustLib
    .instance
    .api
    .crateApiSettingsManagerSaveSettings(settings: settings);

class LauncherSettings {
  final String instanceDir;

  const LauncherSettings({required this.instanceDir});

  @override
  int get hashCode => instanceDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LauncherSettings &&
          runtimeType == other.runtimeType &&
          instanceDir == other.instanceDir;
}
