// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'downloader.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `download_file_sync`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AssetIndexRef`, `AssetIndex`, `AssetObject`, `DownloadArtifact`, `LibraryDownloads`, `Library`, `VersionDownloads`, `VersionEntry`, `VersionInfo`, `VersionManifestV2`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<String>> getVanillaVersions() =>
    RustLib.instance.api.crateApiVanillaManagerGetVanillaVersions();

Stream<DownloadProgress> installVanillaVersion({
  required String versionId,
  required String instanceName,
  required String instancePath,
}) => RustLib.instance.api.crateApiVanillaManagerInstallVanillaVersion(
  versionId: versionId,
  instanceName: instanceName,
  instancePath: instancePath,
);
